services:
  - type: web
    name: suimon-bot
    env: python
    plan: free
    buildCommand: "pip install -r requirements.txt"
    startCommand: "uvicorn bot:fastapi_app --host 0.0.0.0 --port $PORT"
    envVars:
      - key: TELEGRAM_BOT_TOKEN
        value: "YOUR_TELEGRAM_BOT_TOKEN"
      - key: OPENAI_API_KEY
        value: "YOUR_OPENAI_API_KEY"
